# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/replication/v1/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/api/replication/v1/message.proto',
  package='temporal.api.replication.v1',
  syntax='proto3',
  serialized_options=b'\n\036io.temporal.api.replication.v1B\014MessageProtoP\001Z-go.temporal.io/api/replication/v1;replication',
  serialized_pb=b'\n)temporal/api/replication/v1/message.proto\x12\x1btemporal.api.replication.v1\"0\n\x18\x43lusterReplicationConfig\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\"\x82\x01\n\x1aNamespaceReplicationConfig\x12\x1b\n\x13\x61\x63tive_cluster_name\x18\x01 \x01(\t\x12G\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x35.temporal.api.replication.v1.ClusterReplicationConfigB_\n\x1eio.temporal.api.replication.v1B\x0cMessageProtoP\x01Z-go.temporal.io/api/replication/v1;replicationb\x06proto3'
)




_CLUSTERREPLICATIONCONFIG = _descriptor.Descriptor(
  name='ClusterReplicationConfig',
  full_name='temporal.api.replication.v1.ClusterReplicationConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='temporal.api.replication.v1.ClusterReplicationConfig.cluster_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=122,
)


_NAMESPACEREPLICATIONCONFIG = _descriptor.Descriptor(
  name='NamespaceReplicationConfig',
  full_name='temporal.api.replication.v1.NamespaceReplicationConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active_cluster_name', full_name='temporal.api.replication.v1.NamespaceReplicationConfig.active_cluster_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusters', full_name='temporal.api.replication.v1.NamespaceReplicationConfig.clusters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=255,
)

_NAMESPACEREPLICATIONCONFIG.fields_by_name['clusters'].message_type = _CLUSTERREPLICATIONCONFIG
DESCRIPTOR.message_types_by_name['ClusterReplicationConfig'] = _CLUSTERREPLICATIONCONFIG
DESCRIPTOR.message_types_by_name['NamespaceReplicationConfig'] = _NAMESPACEREPLICATIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClusterReplicationConfig = _reflection.GeneratedProtocolMessageType('ClusterReplicationConfig', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERREPLICATIONCONFIG,
  '__module__' : 'temporal.api.replication.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.replication.v1.ClusterReplicationConfig)
  })
_sym_db.RegisterMessage(ClusterReplicationConfig)

NamespaceReplicationConfig = _reflection.GeneratedProtocolMessageType('NamespaceReplicationConfig', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACEREPLICATIONCONFIG,
  '__module__' : 'temporal.api.replication.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.replication.v1.NamespaceReplicationConfig)
  })
_sym_db.RegisterMessage(NamespaceReplicationConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
