# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter/enum.proto',
  package='filter',
  syntax='proto3',
  serialized_options=b'\n\030io.temporal.proto.filterP\001Z$go.temporal.io/temporal-proto/filter',
  serialized_pb=b'\n\x11\x66ilter/enum.proto\x12\x06\x66ilter*\x97\x01\n\x16HistoryEventFilterType\x12)\n%HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED\x10\x00\x12\'\n#HISTORY_EVENT_FILTER_TYPE_ALL_EVENT\x10\x01\x12)\n%HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT\x10\x02\x42\x42\n\x18io.temporal.proto.filterP\x01Z$go.temporal.io/temporal-proto/filterb\x06proto3'
)

_HISTORYEVENTFILTERTYPE = _descriptor.EnumDescriptor(
  name='HistoryEventFilterType',
  full_name='filter.HistoryEventFilterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTORY_EVENT_FILTER_TYPE_ALL_EVENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=30,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_HISTORYEVENTFILTERTYPE)

HistoryEventFilterType = enum_type_wrapper.EnumTypeWrapper(_HISTORYEVENTFILTERTYPE)
HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED = 0
HISTORY_EVENT_FILTER_TYPE_ALL_EVENT = 1
HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT = 2


DESCRIPTOR.enum_types_by_name['HistoryEventFilterType'] = _HISTORYEVENTFILTERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
