# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from execution import enum_pb2 as execution_dot_enum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter/message.proto',
  package='filter',
  syntax='proto3',
  serialized_options=b'\n\030io.temporal.proto.filterP\001Z$go.temporal.io/temporal-proto/filter',
  serialized_pb=b'\n\x14\x66ilter/message.proto\x12\x06\x66ilter\x1a\x14\x65xecution/enum.proto\"<\n\x17WorkflowExecutionFilter\x12\x12\n\nworkflowId\x18\x01 \x01(\t\x12\r\n\x05runId\x18\x02 \x01(\t\"\"\n\x12WorkflowTypeFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\";\n\x0fStartTimeFilter\x12\x14\n\x0c\x65\x61rliestTime\x18\x01 \x01(\x03\x12\x12\n\nlatestTime\x18\x02 \x01(\x03\"B\n\x0cStatusFilter\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".execution.WorkflowExecutionStatusBB\n\x18io.temporal.proto.filterP\x01Z$go.temporal.io/temporal-proto/filterb\x06proto3'
  ,
  dependencies=[execution_dot_enum__pb2.DESCRIPTOR,])




_WORKFLOWEXECUTIONFILTER = _descriptor.Descriptor(
  name='WorkflowExecutionFilter',
  full_name='filter.WorkflowExecutionFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='filter.WorkflowExecutionFilter.workflowId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runId', full_name='filter.WorkflowExecutionFilter.runId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=114,
)


_WORKFLOWTYPEFILTER = _descriptor.Descriptor(
  name='WorkflowTypeFilter',
  full_name='filter.WorkflowTypeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='filter.WorkflowTypeFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=150,
)


_STARTTIMEFILTER = _descriptor.Descriptor(
  name='StartTimeFilter',
  full_name='filter.StartTimeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='earliestTime', full_name='filter.StartTimeFilter.earliestTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latestTime', full_name='filter.StartTimeFilter.latestTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=211,
)


_STATUSFILTER = _descriptor.Descriptor(
  name='StatusFilter',
  full_name='filter.StatusFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='filter.StatusFilter.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=279,
)

_STATUSFILTER.fields_by_name['status'].enum_type = execution_dot_enum__pb2._WORKFLOWEXECUTIONSTATUS
DESCRIPTOR.message_types_by_name['WorkflowExecutionFilter'] = _WORKFLOWEXECUTIONFILTER
DESCRIPTOR.message_types_by_name['WorkflowTypeFilter'] = _WORKFLOWTYPEFILTER
DESCRIPTOR.message_types_by_name['StartTimeFilter'] = _STARTTIMEFILTER
DESCRIPTOR.message_types_by_name['StatusFilter'] = _STATUSFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowExecutionFilter = _reflection.GeneratedProtocolMessageType('WorkflowExecutionFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONFILTER,
  '__module__' : 'filter.message_pb2'
  # @@protoc_insertion_point(class_scope:filter.WorkflowExecutionFilter)
  })
_sym_db.RegisterMessage(WorkflowExecutionFilter)

WorkflowTypeFilter = _reflection.GeneratedProtocolMessageType('WorkflowTypeFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWTYPEFILTER,
  '__module__' : 'filter.message_pb2'
  # @@protoc_insertion_point(class_scope:filter.WorkflowTypeFilter)
  })
_sym_db.RegisterMessage(WorkflowTypeFilter)

StartTimeFilter = _reflection.GeneratedProtocolMessageType('StartTimeFilter', (_message.Message,), {
  'DESCRIPTOR' : _STARTTIMEFILTER,
  '__module__' : 'filter.message_pb2'
  # @@protoc_insertion_point(class_scope:filter.StartTimeFilter)
  })
_sym_db.RegisterMessage(StartTimeFilter)

StatusFilter = _reflection.GeneratedProtocolMessageType('StatusFilter', (_message.Message,), {
  'DESCRIPTOR' : _STATUSFILTER,
  '__module__' : 'filter.message_pb2'
  # @@protoc_insertion_point(class_scope:filter.StatusFilter)
  })
_sym_db.RegisterMessage(StatusFilter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
