# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namespace/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='namespace/enum.proto',
  package='namespace',
  syntax='proto3',
  serialized_options=b'\n\033io.temporal.proto.namespaceP\001Z\'go.temporal.io/temporal-proto/namespace',
  serialized_pb=b'\n\x14namespace/enum.proto\x12\tnamespace*\x93\x01\n\x0fNamespaceStatus\x12 \n\x1cNAMESPACE_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bNAMESPACE_STATUS_REGISTERED\x10\x01\x12\x1f\n\x1bNAMESPACE_STATUS_DEPRECATED\x10\x02\x12\x1c\n\x18NAMESPACE_STATUS_DELETED\x10\x03*l\n\x0e\x41rchivalStatus\x12\x1f\n\x1b\x41RCHIVAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x41RCHIVAL_STATUS_DISABLED\x10\x01\x12\x1b\n\x17\x41RCHIVAL_STATUS_ENABLED\x10\x02\x42H\n\x1bio.temporal.proto.namespaceP\x01Z\'go.temporal.io/temporal-proto/namespaceb\x06proto3'
)

_NAMESPACESTATUS = _descriptor.EnumDescriptor(
  name='NamespaceStatus',
  full_name='namespace.NamespaceStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATUS_REGISTERED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATUS_DEPRECATED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATUS_DELETED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=183,
)
_sym_db.RegisterEnumDescriptor(_NAMESPACESTATUS)

NamespaceStatus = enum_type_wrapper.EnumTypeWrapper(_NAMESPACESTATUS)
_ARCHIVALSTATUS = _descriptor.EnumDescriptor(
  name='ArchivalStatus',
  full_name='namespace.ArchivalStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATUS_DISABLED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATUS_ENABLED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=185,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_ARCHIVALSTATUS)

ArchivalStatus = enum_type_wrapper.EnumTypeWrapper(_ARCHIVALSTATUS)
NAMESPACE_STATUS_UNSPECIFIED = 0
NAMESPACE_STATUS_REGISTERED = 1
NAMESPACE_STATUS_DEPRECATED = 2
NAMESPACE_STATUS_DELETED = 3
ARCHIVAL_STATUS_UNSPECIFIED = 0
ARCHIVAL_STATUS_DISABLED = 1
ARCHIVAL_STATUS_ENABLED = 2


DESCRIPTOR.enum_types_by_name['NamespaceStatus'] = _NAMESPACESTATUS
DESCRIPTOR.enum_types_by_name['ArchivalStatus'] = _ARCHIVALSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
