# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/enums/v1/decision_type.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/enums/v1/decision_type.proto',
  package='temporal.enums.v1',
  syntax='proto3',
  serialized_options=b'\n\024io.temporal.enums.v1B\021DecisionTypeProtoP\001Z,go.temporal.io/temporal-proto/enums/v1;enums',
  serialized_pb=b'\n%temporal/enums/v1/decision_type.proto\x12\x11temporal.enums.v1*\xff\x04\n\x0c\x44\x65\x63isionType\x12\x1d\n\x19\x44\x45\x43ISION_TYPE_UNSPECIFIED\x10\x00\x12(\n$DECISION_TYPE_SCHEDULE_ACTIVITY_TASK\x10\x01\x12.\n*DECISION_TYPE_REQUEST_CANCEL_ACTIVITY_TASK\x10\x02\x12\x1d\n\x19\x44\x45\x43ISION_TYPE_START_TIMER\x10\x03\x12-\n)DECISION_TYPE_COMPLETE_WORKFLOW_EXECUTION\x10\x04\x12)\n%DECISION_TYPE_FAIL_WORKFLOW_EXECUTION\x10\x05\x12\x1e\n\x1a\x44\x45\x43ISION_TYPE_CANCEL_TIMER\x10\x06\x12+\n\'DECISION_TYPE_CANCEL_WORKFLOW_EXECUTION\x10\x07\x12<\n8DECISION_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION\x10\x08\x12\x1f\n\x1b\x44\x45\x43ISION_TYPE_RECORD_MARKER\x10\t\x12\x34\n0DECISION_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION\x10\n\x12\x30\n,DECISION_TYPE_START_CHILD_WORKFLOW_EXECUTION\x10\x0b\x12\x34\n0DECISION_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION\x10\x0c\x12\x33\n/DECISION_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES\x10\rBY\n\x14io.temporal.enums.v1B\x11\x44\x65\x63isionTypeProtoP\x01Z,go.temporal.io/temporal-proto/enums/v1;enumsb\x06proto3'
)

_DECISIONTYPE = _descriptor.EnumDescriptor(
  name='DecisionType',
  full_name='temporal.enums.v1.DecisionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_SCHEDULE_ACTIVITY_TASK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_REQUEST_CANCEL_ACTIVITY_TASK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_START_TIMER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_COMPLETE_WORKFLOW_EXECUTION', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_FAIL_WORKFLOW_EXECUTION', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_CANCEL_TIMER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_CANCEL_WORKFLOW_EXECUTION', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_RECORD_MARKER', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_START_CHILD_WORKFLOW_EXECUTION', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=61,
  serialized_end=700,
)
_sym_db.RegisterEnumDescriptor(_DECISIONTYPE)

DecisionType = enum_type_wrapper.EnumTypeWrapper(_DECISIONTYPE)
DECISION_TYPE_UNSPECIFIED = 0
DECISION_TYPE_SCHEDULE_ACTIVITY_TASK = 1
DECISION_TYPE_REQUEST_CANCEL_ACTIVITY_TASK = 2
DECISION_TYPE_START_TIMER = 3
DECISION_TYPE_COMPLETE_WORKFLOW_EXECUTION = 4
DECISION_TYPE_FAIL_WORKFLOW_EXECUTION = 5
DECISION_TYPE_CANCEL_TIMER = 6
DECISION_TYPE_CANCEL_WORKFLOW_EXECUTION = 7
DECISION_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION = 8
DECISION_TYPE_RECORD_MARKER = 9
DECISION_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION = 10
DECISION_TYPE_START_CHILD_WORKFLOW_EXECUTION = 11
DECISION_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION = 12
DECISION_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES = 13


DESCRIPTOR.enum_types_by_name['DecisionType'] = _DECISIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
