# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/enums/v1/task_queue.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/enums/v1/task_queue.proto',
  package='temporal.enums.v1',
  syntax='proto3',
  serialized_options=b'\n\024io.temporal.enums.v1B\016TaskQueueProtoP\001Z,go.temporal.io/temporal-proto/enums/v1;enums',
  serialized_pb=b'\n\"temporal/enums/v1/task_queue.proto\x12\x11temporal.enums.v1*h\n\rTaskQueueKind\x12\x1f\n\x1bTASK_QUEUE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n\x16TASK_QUEUE_KIND_NORMAL\x10\x01\x12\x1a\n\x16TASK_QUEUE_KIND_STICKY\x10\x02*l\n\rTaskQueueType\x12\x1f\n\x1bTASK_QUEUE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18TASK_QUEUE_TYPE_DECISION\x10\x01\x12\x1c\n\x18TASK_QUEUE_TYPE_ACTIVITY\x10\x02\x42V\n\x14io.temporal.enums.v1B\x0eTaskQueueProtoP\x01Z,go.temporal.io/temporal-proto/enums/v1;enumsb\x06proto3'
)

_TASKQUEUEKIND = _descriptor.EnumDescriptor(
  name='TaskQueueKind',
  full_name='temporal.enums.v1.TaskQueueKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_KIND_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_KIND_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_KIND_STICKY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=57,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_TASKQUEUEKIND)

TaskQueueKind = enum_type_wrapper.EnumTypeWrapper(_TASKQUEUEKIND)
_TASKQUEUETYPE = _descriptor.EnumDescriptor(
  name='TaskQueueType',
  full_name='temporal.enums.v1.TaskQueueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_TYPE_DECISION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_QUEUE_TYPE_ACTIVITY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=271,
)
_sym_db.RegisterEnumDescriptor(_TASKQUEUETYPE)

TaskQueueType = enum_type_wrapper.EnumTypeWrapper(_TASKQUEUETYPE)
TASK_QUEUE_KIND_UNSPECIFIED = 0
TASK_QUEUE_KIND_NORMAL = 1
TASK_QUEUE_KIND_STICKY = 2
TASK_QUEUE_TYPE_UNSPECIFIED = 0
TASK_QUEUE_TYPE_DECISION = 1
TASK_QUEUE_TYPE_ACTIVITY = 2


DESCRIPTOR.enum_types_by_name['TaskQueueKind'] = _TASKQUEUEKIND
DESCRIPTOR.enum_types_by_name['TaskQueueType'] = _TASKQUEUETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
