# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/errordetails/v1/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/errordetails/v1/message.proto',
  package='temporal.errordetails.v1',
  syntax='proto3',
  serialized_options=b'\n!io.temporal.proto.errordetails.v1B\014MessageProtoP\001Z:go.temporal.io/temporal-proto/errordetails/v1;errordetails',
  serialized_pb=b'\n&temporal/errordetails/v1/message.proto\x12\x18temporal.errordetails.v1\"B\n\x0fNotFoundFailure\x12\x17\n\x0f\x63urrent_cluster\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63tive_cluster\x18\x02 \x01(\t\"R\n&WorkflowExecutionAlreadyStartedFailure\x12\x18\n\x10start_request_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"_\n\x19NamespaceNotActiveFailure\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_cluster\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tive_cluster\x18\x03 \x01(\t\"d\n\x10RetryTaskFailure\x12\x14\n\x0cnamespace_id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x15\n\rnext_event_id\x18\x04 \x01(\x03\"\xb5\x01\n\x12RetryTaskV2Failure\x12\x14\n\x0cnamespace_id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x16\n\x0estart_event_id\x18\x04 \x01(\x03\x12\x1b\n\x13start_event_version\x18\x05 \x01(\x03\x12\x14\n\x0c\x65nd_event_id\x18\x06 \x01(\x03\x12\x19\n\x11\x65nd_event_version\x18\x07 \x01(\x03\"k\n ClientVersionNotSupportedFailure\x12\x16\n\x0e\x63lient_version\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_impl\x18\x02 \x01(\t\x12\x1a\n\x12supported_versions\x18\x03 \x01(\t\"i\n!FeatureVersionNotSupportedFailure\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x17\n\x0f\x66\x65\x61ture_version\x18\x02 \x01(\t\x12\x1a\n\x12supported_versions\x18\x03 \x01(\t\";\n\x1b\x43urrentBranchChangedFailure\x12\x1c\n\x14\x63urrent_branch_token\x18\x01 \x01(\x0c\"*\n\x19ShardOwnershipLostFailure\x12\r\n\x05owner\x18\x01 \x01(\t\"\x1f\n\x1dNamespaceAlreadyExistsFailure\"%\n#CancellationAlreadyRequestedFailure\"\x14\n\x12QueryFailedFailure\"\x1c\n\x1a\x45ventAlreadyStartedFailureBo\n!io.temporal.proto.errordetails.v1B\x0cMessageProtoP\x01Z:go.temporal.io/temporal-proto/errordetails/v1;errordetailsb\x06proto3'
)




_NOTFOUNDFAILURE = _descriptor.Descriptor(
  name='NotFoundFailure',
  full_name='temporal.errordetails.v1.NotFoundFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_cluster', full_name='temporal.errordetails.v1.NotFoundFailure.current_cluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_cluster', full_name='temporal.errordetails.v1.NotFoundFailure.active_cluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=134,
)


_WORKFLOWEXECUTIONALREADYSTARTEDFAILURE = _descriptor.Descriptor(
  name='WorkflowExecutionAlreadyStartedFailure',
  full_name='temporal.errordetails.v1.WorkflowExecutionAlreadyStartedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_request_id', full_name='temporal.errordetails.v1.WorkflowExecutionAlreadyStartedFailure.start_request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='temporal.errordetails.v1.WorkflowExecutionAlreadyStartedFailure.run_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=218,
)


_NAMESPACENOTACTIVEFAILURE = _descriptor.Descriptor(
  name='NamespaceNotActiveFailure',
  full_name='temporal.errordetails.v1.NamespaceNotActiveFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='temporal.errordetails.v1.NamespaceNotActiveFailure.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_cluster', full_name='temporal.errordetails.v1.NamespaceNotActiveFailure.current_cluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_cluster', full_name='temporal.errordetails.v1.NamespaceNotActiveFailure.active_cluster', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=315,
)


_RETRYTASKFAILURE = _descriptor.Descriptor(
  name='RetryTaskFailure',
  full_name='temporal.errordetails.v1.RetryTaskFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace_id', full_name='temporal.errordetails.v1.RetryTaskFailure.namespace_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='temporal.errordetails.v1.RetryTaskFailure.workflow_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='temporal.errordetails.v1.RetryTaskFailure.run_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_event_id', full_name='temporal.errordetails.v1.RetryTaskFailure.next_event_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=417,
)


_RETRYTASKV2FAILURE = _descriptor.Descriptor(
  name='RetryTaskV2Failure',
  full_name='temporal.errordetails.v1.RetryTaskV2Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace_id', full_name='temporal.errordetails.v1.RetryTaskV2Failure.namespace_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='temporal.errordetails.v1.RetryTaskV2Failure.workflow_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='temporal.errordetails.v1.RetryTaskV2Failure.run_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_event_id', full_name='temporal.errordetails.v1.RetryTaskV2Failure.start_event_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_event_version', full_name='temporal.errordetails.v1.RetryTaskV2Failure.start_event_version', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_event_id', full_name='temporal.errordetails.v1.RetryTaskV2Failure.end_event_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_event_version', full_name='temporal.errordetails.v1.RetryTaskV2Failure.end_event_version', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=601,
)


_CLIENTVERSIONNOTSUPPORTEDFAILURE = _descriptor.Descriptor(
  name='ClientVersionNotSupportedFailure',
  full_name='temporal.errordetails.v1.ClientVersionNotSupportedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_version', full_name='temporal.errordetails.v1.ClientVersionNotSupportedFailure.client_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_impl', full_name='temporal.errordetails.v1.ClientVersionNotSupportedFailure.client_impl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supported_versions', full_name='temporal.errordetails.v1.ClientVersionNotSupportedFailure.supported_versions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=710,
)


_FEATUREVERSIONNOTSUPPORTEDFAILURE = _descriptor.Descriptor(
  name='FeatureVersionNotSupportedFailure',
  full_name='temporal.errordetails.v1.FeatureVersionNotSupportedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='temporal.errordetails.v1.FeatureVersionNotSupportedFailure.feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_version', full_name='temporal.errordetails.v1.FeatureVersionNotSupportedFailure.feature_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supported_versions', full_name='temporal.errordetails.v1.FeatureVersionNotSupportedFailure.supported_versions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=817,
)


_CURRENTBRANCHCHANGEDFAILURE = _descriptor.Descriptor(
  name='CurrentBranchChangedFailure',
  full_name='temporal.errordetails.v1.CurrentBranchChangedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_branch_token', full_name='temporal.errordetails.v1.CurrentBranchChangedFailure.current_branch_token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=819,
  serialized_end=878,
)


_SHARDOWNERSHIPLOSTFAILURE = _descriptor.Descriptor(
  name='ShardOwnershipLostFailure',
  full_name='temporal.errordetails.v1.ShardOwnershipLostFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='temporal.errordetails.v1.ShardOwnershipLostFailure.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=880,
  serialized_end=922,
)


_NAMESPACEALREADYEXISTSFAILURE = _descriptor.Descriptor(
  name='NamespaceAlreadyExistsFailure',
  full_name='temporal.errordetails.v1.NamespaceAlreadyExistsFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=924,
  serialized_end=955,
)


_CANCELLATIONALREADYREQUESTEDFAILURE = _descriptor.Descriptor(
  name='CancellationAlreadyRequestedFailure',
  full_name='temporal.errordetails.v1.CancellationAlreadyRequestedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=957,
  serialized_end=994,
)


_QUERYFAILEDFAILURE = _descriptor.Descriptor(
  name='QueryFailedFailure',
  full_name='temporal.errordetails.v1.QueryFailedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=996,
  serialized_end=1016,
)


_EVENTALREADYSTARTEDFAILURE = _descriptor.Descriptor(
  name='EventAlreadyStartedFailure',
  full_name='temporal.errordetails.v1.EventAlreadyStartedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1018,
  serialized_end=1046,
)

DESCRIPTOR.message_types_by_name['NotFoundFailure'] = _NOTFOUNDFAILURE
DESCRIPTOR.message_types_by_name['WorkflowExecutionAlreadyStartedFailure'] = _WORKFLOWEXECUTIONALREADYSTARTEDFAILURE
DESCRIPTOR.message_types_by_name['NamespaceNotActiveFailure'] = _NAMESPACENOTACTIVEFAILURE
DESCRIPTOR.message_types_by_name['RetryTaskFailure'] = _RETRYTASKFAILURE
DESCRIPTOR.message_types_by_name['RetryTaskV2Failure'] = _RETRYTASKV2FAILURE
DESCRIPTOR.message_types_by_name['ClientVersionNotSupportedFailure'] = _CLIENTVERSIONNOTSUPPORTEDFAILURE
DESCRIPTOR.message_types_by_name['FeatureVersionNotSupportedFailure'] = _FEATUREVERSIONNOTSUPPORTEDFAILURE
DESCRIPTOR.message_types_by_name['CurrentBranchChangedFailure'] = _CURRENTBRANCHCHANGEDFAILURE
DESCRIPTOR.message_types_by_name['ShardOwnershipLostFailure'] = _SHARDOWNERSHIPLOSTFAILURE
DESCRIPTOR.message_types_by_name['NamespaceAlreadyExistsFailure'] = _NAMESPACEALREADYEXISTSFAILURE
DESCRIPTOR.message_types_by_name['CancellationAlreadyRequestedFailure'] = _CANCELLATIONALREADYREQUESTEDFAILURE
DESCRIPTOR.message_types_by_name['QueryFailedFailure'] = _QUERYFAILEDFAILURE
DESCRIPTOR.message_types_by_name['EventAlreadyStartedFailure'] = _EVENTALREADYSTARTEDFAILURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotFoundFailure = _reflection.GeneratedProtocolMessageType('NotFoundFailure', (_message.Message,), {
  'DESCRIPTOR' : _NOTFOUNDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.NotFoundFailure)
  })
_sym_db.RegisterMessage(NotFoundFailure)

WorkflowExecutionAlreadyStartedFailure = _reflection.GeneratedProtocolMessageType('WorkflowExecutionAlreadyStartedFailure', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONALREADYSTARTEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.WorkflowExecutionAlreadyStartedFailure)
  })
_sym_db.RegisterMessage(WorkflowExecutionAlreadyStartedFailure)

NamespaceNotActiveFailure = _reflection.GeneratedProtocolMessageType('NamespaceNotActiveFailure', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACENOTACTIVEFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.NamespaceNotActiveFailure)
  })
_sym_db.RegisterMessage(NamespaceNotActiveFailure)

RetryTaskFailure = _reflection.GeneratedProtocolMessageType('RetryTaskFailure', (_message.Message,), {
  'DESCRIPTOR' : _RETRYTASKFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.RetryTaskFailure)
  })
_sym_db.RegisterMessage(RetryTaskFailure)

RetryTaskV2Failure = _reflection.GeneratedProtocolMessageType('RetryTaskV2Failure', (_message.Message,), {
  'DESCRIPTOR' : _RETRYTASKV2FAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.RetryTaskV2Failure)
  })
_sym_db.RegisterMessage(RetryTaskV2Failure)

ClientVersionNotSupportedFailure = _reflection.GeneratedProtocolMessageType('ClientVersionNotSupportedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTVERSIONNOTSUPPORTEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.ClientVersionNotSupportedFailure)
  })
_sym_db.RegisterMessage(ClientVersionNotSupportedFailure)

FeatureVersionNotSupportedFailure = _reflection.GeneratedProtocolMessageType('FeatureVersionNotSupportedFailure', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVERSIONNOTSUPPORTEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.FeatureVersionNotSupportedFailure)
  })
_sym_db.RegisterMessage(FeatureVersionNotSupportedFailure)

CurrentBranchChangedFailure = _reflection.GeneratedProtocolMessageType('CurrentBranchChangedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTBRANCHCHANGEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.CurrentBranchChangedFailure)
  })
_sym_db.RegisterMessage(CurrentBranchChangedFailure)

ShardOwnershipLostFailure = _reflection.GeneratedProtocolMessageType('ShardOwnershipLostFailure', (_message.Message,), {
  'DESCRIPTOR' : _SHARDOWNERSHIPLOSTFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.ShardOwnershipLostFailure)
  })
_sym_db.RegisterMessage(ShardOwnershipLostFailure)

NamespaceAlreadyExistsFailure = _reflection.GeneratedProtocolMessageType('NamespaceAlreadyExistsFailure', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACEALREADYEXISTSFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.NamespaceAlreadyExistsFailure)
  })
_sym_db.RegisterMessage(NamespaceAlreadyExistsFailure)

CancellationAlreadyRequestedFailure = _reflection.GeneratedProtocolMessageType('CancellationAlreadyRequestedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CANCELLATIONALREADYREQUESTEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.CancellationAlreadyRequestedFailure)
  })
_sym_db.RegisterMessage(CancellationAlreadyRequestedFailure)

QueryFailedFailure = _reflection.GeneratedProtocolMessageType('QueryFailedFailure', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFAILEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.QueryFailedFailure)
  })
_sym_db.RegisterMessage(QueryFailedFailure)

EventAlreadyStartedFailure = _reflection.GeneratedProtocolMessageType('EventAlreadyStartedFailure', (_message.Message,), {
  'DESCRIPTOR' : _EVENTALREADYSTARTEDFAILURE,
  '__module__' : 'temporal.errordetails.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.errordetails.v1.EventAlreadyStartedFailure)
  })
_sym_db.RegisterMessage(EventAlreadyStartedFailure)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
