# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/query/v1/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.enums.v1 import query_pb2 as temporal_dot_enums_dot_v1_dot_query__pb2
from temporal.enums.v1 import workflow_pb2 as temporal_dot_enums_dot_v1_dot_workflow__pb2
from temporal.common.v1 import message_pb2 as temporal_dot_common_dot_v1_dot_message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/query/v1/message.proto',
  package='temporal.query.v1',
  syntax='proto3',
  serialized_options=b'\n\032io.temporal.proto.query.v1B\014MessageProtoP\001Z,go.temporal.io/temporal-proto/query/v1;query',
  serialized_pb=b'\n\x1ftemporal/query/v1/message.proto\x12\x11temporal.query.v1\x1a\x1dtemporal/enums/v1/query.proto\x1a temporal/enums/v1/workflow.proto\x1a temporal/common/v1/message.proto\"U\n\rWorkflowQuery\x12\x12\n\nquery_type\x18\x01 \x01(\t\x12\x30\n\nquery_args\x18\x02 \x01(\x0b\x32\x1c.temporal.common.v1.Payloads\"\x93\x01\n\x13WorkflowQueryResult\x12\x37\n\x0bresult_type\x18\x01 \x01(\x0e\x32\".temporal.enums.v1.QueryResultType\x12,\n\x06\x61nswer\x18\x02 \x01(\x0b\x32\x1c.temporal.common.v1.Payloads\x12\x15\n\rerror_message\x18\x03 \x01(\t\"K\n\rQueryRejected\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.temporal.enums.v1.WorkflowExecutionStatusBZ\n\x1aio.temporal.proto.query.v1B\x0cMessageProtoP\x01Z,go.temporal.io/temporal-proto/query/v1;queryb\x06proto3'
  ,
  dependencies=[temporal_dot_enums_dot_v1_dot_query__pb2.DESCRIPTOR,temporal_dot_enums_dot_v1_dot_workflow__pb2.DESCRIPTOR,temporal_dot_common_dot_v1_dot_message__pb2.DESCRIPTOR,])




_WORKFLOWQUERY = _descriptor.Descriptor(
  name='WorkflowQuery',
  full_name='temporal.query.v1.WorkflowQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_type', full_name='temporal.query.v1.WorkflowQuery.query_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_args', full_name='temporal.query.v1.WorkflowQuery.query_args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=238,
)


_WORKFLOWQUERYRESULT = _descriptor.Descriptor(
  name='WorkflowQueryResult',
  full_name='temporal.query.v1.WorkflowQueryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_type', full_name='temporal.query.v1.WorkflowQueryResult.result_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answer', full_name='temporal.query.v1.WorkflowQueryResult.answer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='temporal.query.v1.WorkflowQueryResult.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=388,
)


_QUERYREJECTED = _descriptor.Descriptor(
  name='QueryRejected',
  full_name='temporal.query.v1.QueryRejected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='temporal.query.v1.QueryRejected.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=465,
)

_WORKFLOWQUERY.fields_by_name['query_args'].message_type = temporal_dot_common_dot_v1_dot_message__pb2._PAYLOADS
_WORKFLOWQUERYRESULT.fields_by_name['result_type'].enum_type = temporal_dot_enums_dot_v1_dot_query__pb2._QUERYRESULTTYPE
_WORKFLOWQUERYRESULT.fields_by_name['answer'].message_type = temporal_dot_common_dot_v1_dot_message__pb2._PAYLOADS
_QUERYREJECTED.fields_by_name['status'].enum_type = temporal_dot_enums_dot_v1_dot_workflow__pb2._WORKFLOWEXECUTIONSTATUS
DESCRIPTOR.message_types_by_name['WorkflowQuery'] = _WORKFLOWQUERY
DESCRIPTOR.message_types_by_name['WorkflowQueryResult'] = _WORKFLOWQUERYRESULT
DESCRIPTOR.message_types_by_name['QueryRejected'] = _QUERYREJECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowQuery = _reflection.GeneratedProtocolMessageType('WorkflowQuery', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWQUERY,
  '__module__' : 'temporal.query.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.query.v1.WorkflowQuery)
  })
_sym_db.RegisterMessage(WorkflowQuery)

WorkflowQueryResult = _reflection.GeneratedProtocolMessageType('WorkflowQueryResult', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWQUERYRESULT,
  '__module__' : 'temporal.query.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.query.v1.WorkflowQueryResult)
  })
_sym_db.RegisterMessage(WorkflowQueryResult)

QueryRejected = _reflection.GeneratedProtocolMessageType('QueryRejected', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREJECTED,
  '__module__' : 'temporal.query.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.query.v1.QueryRejected)
  })
_sym_db.RegisterMessage(QueryRejected)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
