# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution/enum.proto',
  package='execution',
  syntax='proto3',
  serialized_options=b'\n\033io.temporal.proto.executionP\001Z\'go.temporal.io/temporal-proto/execution',
  serialized_pb=b'\n\x14\x65xecution/enum.proto\x12\texecution*\xe5\x02\n\x17WorkflowExecutionStatus\x12)\n%WORKFLOW_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12%\n!WORKFLOW_EXECUTION_STATUS_RUNNING\x10\x01\x12\'\n#WORKFLOW_EXECUTION_STATUS_COMPLETED\x10\x02\x12$\n WORKFLOW_EXECUTION_STATUS_FAILED\x10\x03\x12&\n\"WORKFLOW_EXECUTION_STATUS_CANCELED\x10\x04\x12(\n$WORKFLOW_EXECUTION_STATUS_TERMINATED\x10\x05\x12.\n*WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW\x10\x06\x12\'\n#WORKFLOW_EXECUTION_STATUS_TIMED_OUT\x10\x07*\xb5\x01\n\x14PendingActivityState\x12&\n\"PENDING_ACTIVITY_STATE_UNSPECIFIED\x10\x00\x12$\n PENDING_ACTIVITY_STATE_SCHEDULED\x10\x01\x12\"\n\x1ePENDING_ACTIVITY_STATE_STARTED\x10\x02\x12+\n\'PENDING_ACTIVITY_STATE_CANCEL_REQUESTED\x10\x03\x42H\n\x1bio.temporal.proto.executionP\x01Z\'go.temporal.io/temporal-proto/executionb\x06proto3'
)

_WORKFLOWEXECUTIONSTATUS = _descriptor.EnumDescriptor(
  name='WorkflowExecutionStatus',
  full_name='execution.WorkflowExecutionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_RUNNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_FAILED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_CANCELED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_TERMINATED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKFLOW_EXECUTION_STATUS_TIMED_OUT', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=36,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_WORKFLOWEXECUTIONSTATUS)

WorkflowExecutionStatus = enum_type_wrapper.EnumTypeWrapper(_WORKFLOWEXECUTIONSTATUS)
_PENDINGACTIVITYSTATE = _descriptor.EnumDescriptor(
  name='PendingActivityState',
  full_name='execution.PendingActivityState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING_ACTIVITY_STATE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING_ACTIVITY_STATE_SCHEDULED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING_ACTIVITY_STATE_STARTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING_ACTIVITY_STATE_CANCEL_REQUESTED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=396,
  serialized_end=577,
)
_sym_db.RegisterEnumDescriptor(_PENDINGACTIVITYSTATE)

PendingActivityState = enum_type_wrapper.EnumTypeWrapper(_PENDINGACTIVITYSTATE)
WORKFLOW_EXECUTION_STATUS_UNSPECIFIED = 0
WORKFLOW_EXECUTION_STATUS_RUNNING = 1
WORKFLOW_EXECUTION_STATUS_COMPLETED = 2
WORKFLOW_EXECUTION_STATUS_FAILED = 3
WORKFLOW_EXECUTION_STATUS_CANCELED = 4
WORKFLOW_EXECUTION_STATUS_TERMINATED = 5
WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW = 6
WORKFLOW_EXECUTION_STATUS_TIMED_OUT = 7
PENDING_ACTIVITY_STATE_UNSPECIFIED = 0
PENDING_ACTIVITY_STATE_SCHEDULED = 1
PENDING_ACTIVITY_STATE_STARTED = 2
PENDING_ACTIVITY_STATE_CANCEL_REQUESTED = 3


DESCRIPTOR.enum_types_by_name['WorkflowExecutionStatus'] = _WORKFLOWEXECUTIONSTATUS
DESCRIPTOR.enum_types_by_name['PendingActivityState'] = _PENDINGACTIVITYSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
