# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errordetails/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='errordetails/message.proto',
  package='errordetails',
  syntax='proto3',
  serialized_options=b'\n\036io.temporal.proto.errordetailsP\001Z*go.temporal.io/temporal-proto/errordetails',
  serialized_pb=b'\n\x1a\x65rrordetails/message.proto\x12\x0c\x65rrordetails\"@\n\x0fNotFoundFailure\x12\x16\n\x0e\x63urrentCluster\x18\x01 \x01(\t\x12\x15\n\ractiveCluster\x18\x02 \x01(\t\"O\n&WorkflowExecutionAlreadyStartedFailure\x12\x16\n\x0estartRequestId\x18\x01 \x01(\t\x12\r\n\x05runId\x18\x02 \x01(\t\"]\n\x19NamespaceNotActiveFailure\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x16\n\x0e\x63urrentCluster\x18\x02 \x01(\t\x12\x15\n\ractiveCluster\x18\x03 \x01(\t\"_\n\x10RetryTaskFailure\x12\x13\n\x0bnamespaceId\x18\x01 \x01(\t\x12\x12\n\nworkflowId\x18\x02 \x01(\t\x12\r\n\x05runId\x18\x03 \x01(\t\x12\x13\n\x0bnextEventId\x18\x04 \x01(\x03\"\xaa\x01\n\x12RetryTaskV2Failure\x12\x13\n\x0bnamespaceId\x18\x01 \x01(\t\x12\x12\n\nworkflowId\x18\x02 \x01(\t\x12\r\n\x05runId\x18\x03 \x01(\t\x12\x14\n\x0cstartEventId\x18\x04 \x01(\x03\x12\x19\n\x11startEventVersion\x18\x05 \x01(\x03\x12\x12\n\nendEventId\x18\x06 \x01(\x03\x12\x17\n\x0f\x65ndEventVersion\x18\x07 \x01(\x03\"h\n ClientVersionNotSupportedFailure\x12\x15\n\rclientVersion\x18\x01 \x01(\t\x12\x12\n\nclientImpl\x18\x02 \x01(\t\x12\x19\n\x11supportedVersions\x18\x03 \x01(\t\"g\n!FeatureVersionNotSupportedFailure\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x61tureVersion\x18\x02 \x01(\t\x12\x19\n\x11supportedVersions\x18\x03 \x01(\t\"9\n\x1b\x43urrentBranchChangedFailure\x12\x1a\n\x12\x63urrentBranchToken\x18\x01 \x01(\x0c\"*\n\x19ShardOwnershipLostFailure\x12\r\n\x05owner\x18\x01 \x01(\t\"\x1f\n\x1dNamespaceAlreadyExistsFailure\"%\n#CancellationAlreadyRequestedFailure\"\x14\n\x12QueryFailedFailure\"\x1c\n\x1a\x45ventAlreadyStartedFailureBN\n\x1eio.temporal.proto.errordetailsP\x01Z*go.temporal.io/temporal-proto/errordetailsb\x06proto3'
)




_NOTFOUNDFAILURE = _descriptor.Descriptor(
  name='NotFoundFailure',
  full_name='errordetails.NotFoundFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentCluster', full_name='errordetails.NotFoundFailure.currentCluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeCluster', full_name='errordetails.NotFoundFailure.activeCluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=108,
)


_WORKFLOWEXECUTIONALREADYSTARTEDFAILURE = _descriptor.Descriptor(
  name='WorkflowExecutionAlreadyStartedFailure',
  full_name='errordetails.WorkflowExecutionAlreadyStartedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startRequestId', full_name='errordetails.WorkflowExecutionAlreadyStartedFailure.startRequestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runId', full_name='errordetails.WorkflowExecutionAlreadyStartedFailure.runId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=189,
)


_NAMESPACENOTACTIVEFAILURE = _descriptor.Descriptor(
  name='NamespaceNotActiveFailure',
  full_name='errordetails.NamespaceNotActiveFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='errordetails.NamespaceNotActiveFailure.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentCluster', full_name='errordetails.NamespaceNotActiveFailure.currentCluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeCluster', full_name='errordetails.NamespaceNotActiveFailure.activeCluster', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=284,
)


_RETRYTASKFAILURE = _descriptor.Descriptor(
  name='RetryTaskFailure',
  full_name='errordetails.RetryTaskFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespaceId', full_name='errordetails.RetryTaskFailure.namespaceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='errordetails.RetryTaskFailure.workflowId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runId', full_name='errordetails.RetryTaskFailure.runId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nextEventId', full_name='errordetails.RetryTaskFailure.nextEventId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=381,
)


_RETRYTASKV2FAILURE = _descriptor.Descriptor(
  name='RetryTaskV2Failure',
  full_name='errordetails.RetryTaskV2Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespaceId', full_name='errordetails.RetryTaskV2Failure.namespaceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='errordetails.RetryTaskV2Failure.workflowId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runId', full_name='errordetails.RetryTaskV2Failure.runId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startEventId', full_name='errordetails.RetryTaskV2Failure.startEventId', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startEventVersion', full_name='errordetails.RetryTaskV2Failure.startEventVersion', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endEventId', full_name='errordetails.RetryTaskV2Failure.endEventId', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endEventVersion', full_name='errordetails.RetryTaskV2Failure.endEventVersion', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=554,
)


_CLIENTVERSIONNOTSUPPORTEDFAILURE = _descriptor.Descriptor(
  name='ClientVersionNotSupportedFailure',
  full_name='errordetails.ClientVersionNotSupportedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientVersion', full_name='errordetails.ClientVersionNotSupportedFailure.clientVersion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientImpl', full_name='errordetails.ClientVersionNotSupportedFailure.clientImpl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supportedVersions', full_name='errordetails.ClientVersionNotSupportedFailure.supportedVersions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=660,
)


_FEATUREVERSIONNOTSUPPORTEDFAILURE = _descriptor.Descriptor(
  name='FeatureVersionNotSupportedFailure',
  full_name='errordetails.FeatureVersionNotSupportedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='errordetails.FeatureVersionNotSupportedFailure.feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='featureVersion', full_name='errordetails.FeatureVersionNotSupportedFailure.featureVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supportedVersions', full_name='errordetails.FeatureVersionNotSupportedFailure.supportedVersions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=765,
)


_CURRENTBRANCHCHANGEDFAILURE = _descriptor.Descriptor(
  name='CurrentBranchChangedFailure',
  full_name='errordetails.CurrentBranchChangedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentBranchToken', full_name='errordetails.CurrentBranchChangedFailure.currentBranchToken', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=767,
  serialized_end=824,
)


_SHARDOWNERSHIPLOSTFAILURE = _descriptor.Descriptor(
  name='ShardOwnershipLostFailure',
  full_name='errordetails.ShardOwnershipLostFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='errordetails.ShardOwnershipLostFailure.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=868,
)


_NAMESPACEALREADYEXISTSFAILURE = _descriptor.Descriptor(
  name='NamespaceAlreadyExistsFailure',
  full_name='errordetails.NamespaceAlreadyExistsFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=870,
  serialized_end=901,
)


_CANCELLATIONALREADYREQUESTEDFAILURE = _descriptor.Descriptor(
  name='CancellationAlreadyRequestedFailure',
  full_name='errordetails.CancellationAlreadyRequestedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=903,
  serialized_end=940,
)


_QUERYFAILEDFAILURE = _descriptor.Descriptor(
  name='QueryFailedFailure',
  full_name='errordetails.QueryFailedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=942,
  serialized_end=962,
)


_EVENTALREADYSTARTEDFAILURE = _descriptor.Descriptor(
  name='EventAlreadyStartedFailure',
  full_name='errordetails.EventAlreadyStartedFailure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=964,
  serialized_end=992,
)

DESCRIPTOR.message_types_by_name['NotFoundFailure'] = _NOTFOUNDFAILURE
DESCRIPTOR.message_types_by_name['WorkflowExecutionAlreadyStartedFailure'] = _WORKFLOWEXECUTIONALREADYSTARTEDFAILURE
DESCRIPTOR.message_types_by_name['NamespaceNotActiveFailure'] = _NAMESPACENOTACTIVEFAILURE
DESCRIPTOR.message_types_by_name['RetryTaskFailure'] = _RETRYTASKFAILURE
DESCRIPTOR.message_types_by_name['RetryTaskV2Failure'] = _RETRYTASKV2FAILURE
DESCRIPTOR.message_types_by_name['ClientVersionNotSupportedFailure'] = _CLIENTVERSIONNOTSUPPORTEDFAILURE
DESCRIPTOR.message_types_by_name['FeatureVersionNotSupportedFailure'] = _FEATUREVERSIONNOTSUPPORTEDFAILURE
DESCRIPTOR.message_types_by_name['CurrentBranchChangedFailure'] = _CURRENTBRANCHCHANGEDFAILURE
DESCRIPTOR.message_types_by_name['ShardOwnershipLostFailure'] = _SHARDOWNERSHIPLOSTFAILURE
DESCRIPTOR.message_types_by_name['NamespaceAlreadyExistsFailure'] = _NAMESPACEALREADYEXISTSFAILURE
DESCRIPTOR.message_types_by_name['CancellationAlreadyRequestedFailure'] = _CANCELLATIONALREADYREQUESTEDFAILURE
DESCRIPTOR.message_types_by_name['QueryFailedFailure'] = _QUERYFAILEDFAILURE
DESCRIPTOR.message_types_by_name['EventAlreadyStartedFailure'] = _EVENTALREADYSTARTEDFAILURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotFoundFailure = _reflection.GeneratedProtocolMessageType('NotFoundFailure', (_message.Message,), {
  'DESCRIPTOR' : _NOTFOUNDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.NotFoundFailure)
  })
_sym_db.RegisterMessage(NotFoundFailure)

WorkflowExecutionAlreadyStartedFailure = _reflection.GeneratedProtocolMessageType('WorkflowExecutionAlreadyStartedFailure', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONALREADYSTARTEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.WorkflowExecutionAlreadyStartedFailure)
  })
_sym_db.RegisterMessage(WorkflowExecutionAlreadyStartedFailure)

NamespaceNotActiveFailure = _reflection.GeneratedProtocolMessageType('NamespaceNotActiveFailure', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACENOTACTIVEFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.NamespaceNotActiveFailure)
  })
_sym_db.RegisterMessage(NamespaceNotActiveFailure)

RetryTaskFailure = _reflection.GeneratedProtocolMessageType('RetryTaskFailure', (_message.Message,), {
  'DESCRIPTOR' : _RETRYTASKFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.RetryTaskFailure)
  })
_sym_db.RegisterMessage(RetryTaskFailure)

RetryTaskV2Failure = _reflection.GeneratedProtocolMessageType('RetryTaskV2Failure', (_message.Message,), {
  'DESCRIPTOR' : _RETRYTASKV2FAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.RetryTaskV2Failure)
  })
_sym_db.RegisterMessage(RetryTaskV2Failure)

ClientVersionNotSupportedFailure = _reflection.GeneratedProtocolMessageType('ClientVersionNotSupportedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTVERSIONNOTSUPPORTEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.ClientVersionNotSupportedFailure)
  })
_sym_db.RegisterMessage(ClientVersionNotSupportedFailure)

FeatureVersionNotSupportedFailure = _reflection.GeneratedProtocolMessageType('FeatureVersionNotSupportedFailure', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVERSIONNOTSUPPORTEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.FeatureVersionNotSupportedFailure)
  })
_sym_db.RegisterMessage(FeatureVersionNotSupportedFailure)

CurrentBranchChangedFailure = _reflection.GeneratedProtocolMessageType('CurrentBranchChangedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTBRANCHCHANGEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.CurrentBranchChangedFailure)
  })
_sym_db.RegisterMessage(CurrentBranchChangedFailure)

ShardOwnershipLostFailure = _reflection.GeneratedProtocolMessageType('ShardOwnershipLostFailure', (_message.Message,), {
  'DESCRIPTOR' : _SHARDOWNERSHIPLOSTFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.ShardOwnershipLostFailure)
  })
_sym_db.RegisterMessage(ShardOwnershipLostFailure)

NamespaceAlreadyExistsFailure = _reflection.GeneratedProtocolMessageType('NamespaceAlreadyExistsFailure', (_message.Message,), {
  'DESCRIPTOR' : _NAMESPACEALREADYEXISTSFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.NamespaceAlreadyExistsFailure)
  })
_sym_db.RegisterMessage(NamespaceAlreadyExistsFailure)

CancellationAlreadyRequestedFailure = _reflection.GeneratedProtocolMessageType('CancellationAlreadyRequestedFailure', (_message.Message,), {
  'DESCRIPTOR' : _CANCELLATIONALREADYREQUESTEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.CancellationAlreadyRequestedFailure)
  })
_sym_db.RegisterMessage(CancellationAlreadyRequestedFailure)

QueryFailedFailure = _reflection.GeneratedProtocolMessageType('QueryFailedFailure', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFAILEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.QueryFailedFailure)
  })
_sym_db.RegisterMessage(QueryFailedFailure)

EventAlreadyStartedFailure = _reflection.GeneratedProtocolMessageType('EventAlreadyStartedFailure', (_message.Message,), {
  'DESCRIPTOR' : _EVENTALREADYSTARTEDFAILURE,
  '__module__' : 'errordetails.message_pb2'
  # @@protoc_insertion_point(class_scope:errordetails.EventAlreadyStartedFailure)
  })
_sym_db.RegisterMessage(EventAlreadyStartedFailure)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
