# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/filter/v1/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.api.enums.v1 import workflow_pb2 as temporal_dot_api_dot_enums_dot_v1_dot_workflow__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/api/filter/v1/message.proto',
  package='temporal.api.filter.v1',
  syntax='proto3',
  serialized_options=b'\n\031io.temporal.api.filter.v1B\014MessageProtoP\001Z#go.temporal.io/api/filter/v1;filter',
  serialized_pb=b'\n$temporal/api/filter/v1/message.proto\x12\x16temporal.api.filter.v1\x1a$temporal/api/enums/v1/workflow.proto\">\n\x17WorkflowExecutionFilter\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"\"\n\x12WorkflowTypeFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n\x0fStartTimeFilter\x12\x15\n\rearliest_time\x18\x01 \x01(\x03\x12\x13\n\x0blatest_time\x18\x02 \x01(\x03\"N\n\x0cStatusFilter\x12>\n\x06status\x18\x01 \x01(\x0e\x32..temporal.api.enums.v1.WorkflowExecutionStatusBP\n\x19io.temporal.api.filter.v1B\x0cMessageProtoP\x01Z#go.temporal.io/api/filter/v1;filterb\x06proto3'
  ,
  dependencies=[temporal_dot_api_dot_enums_dot_v1_dot_workflow__pb2.DESCRIPTOR,])




_WORKFLOWEXECUTIONFILTER = _descriptor.Descriptor(
  name='WorkflowExecutionFilter',
  full_name='temporal.api.filter.v1.WorkflowExecutionFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_id', full_name='temporal.api.filter.v1.WorkflowExecutionFilter.workflow_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='temporal.api.filter.v1.WorkflowExecutionFilter.run_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=164,
)


_WORKFLOWTYPEFILTER = _descriptor.Descriptor(
  name='WorkflowTypeFilter',
  full_name='temporal.api.filter.v1.WorkflowTypeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='temporal.api.filter.v1.WorkflowTypeFilter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=200,
)


_STARTTIMEFILTER = _descriptor.Descriptor(
  name='StartTimeFilter',
  full_name='temporal.api.filter.v1.StartTimeFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='earliest_time', full_name='temporal.api.filter.v1.StartTimeFilter.earliest_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_time', full_name='temporal.api.filter.v1.StartTimeFilter.latest_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=263,
)


_STATUSFILTER = _descriptor.Descriptor(
  name='StatusFilter',
  full_name='temporal.api.filter.v1.StatusFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='temporal.api.filter.v1.StatusFilter.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=343,
)

_STATUSFILTER.fields_by_name['status'].enum_type = temporal_dot_api_dot_enums_dot_v1_dot_workflow__pb2._WORKFLOWEXECUTIONSTATUS
DESCRIPTOR.message_types_by_name['WorkflowExecutionFilter'] = _WORKFLOWEXECUTIONFILTER
DESCRIPTOR.message_types_by_name['WorkflowTypeFilter'] = _WORKFLOWTYPEFILTER
DESCRIPTOR.message_types_by_name['StartTimeFilter'] = _STARTTIMEFILTER
DESCRIPTOR.message_types_by_name['StatusFilter'] = _STATUSFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowExecutionFilter = _reflection.GeneratedProtocolMessageType('WorkflowExecutionFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONFILTER,
  '__module__' : 'temporal.api.filter.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.filter.v1.WorkflowExecutionFilter)
  })
_sym_db.RegisterMessage(WorkflowExecutionFilter)

WorkflowTypeFilter = _reflection.GeneratedProtocolMessageType('WorkflowTypeFilter', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWTYPEFILTER,
  '__module__' : 'temporal.api.filter.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.filter.v1.WorkflowTypeFilter)
  })
_sym_db.RegisterMessage(WorkflowTypeFilter)

StartTimeFilter = _reflection.GeneratedProtocolMessageType('StartTimeFilter', (_message.Message,), {
  'DESCRIPTOR' : _STARTTIMEFILTER,
  '__module__' : 'temporal.api.filter.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.filter.v1.StartTimeFilter)
  })
_sym_db.RegisterMessage(StartTimeFilter)

StatusFilter = _reflection.GeneratedProtocolMessageType('StatusFilter', (_message.Message,), {
  'DESCRIPTOR' : _STATUSFILTER,
  '__module__' : 'temporal.api.filter.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.api.filter.v1.StatusFilter)
  })
_sym_db.RegisterMessage(StatusFilter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
