# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/enums/v1/namespace.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/api/enums/v1/namespace.proto',
  package='temporal.api.enums.v1',
  syntax='proto3',
  serialized_options=b'\n\030io.temporal.api.enums.v1B\016NamespaceProtoP\001Z!go.temporal.io/api/enums/v1;enums',
  serialized_pb=b'\n%temporal/api/enums/v1/namespace.proto\x12\x15temporal.api.enums.v1*\x8e\x01\n\x0eNamespaceState\x12\x1f\n\x1bNAMESPACE_STATE_UNSPECIFIED\x10\x00\x12\x1e\n\x1aNAMESPACE_STATE_REGISTERED\x10\x01\x12\x1e\n\x1aNAMESPACE_STATE_DEPRECATED\x10\x02\x12\x1b\n\x17NAMESPACE_STATE_DELETED\x10\x03*h\n\rArchivalState\x12\x1e\n\x1a\x41RCHIVAL_STATE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x41RCHIVAL_STATE_DISABLED\x10\x01\x12\x1a\n\x16\x41RCHIVAL_STATE_ENABLED\x10\x02\x42O\n\x18io.temporal.api.enums.v1B\x0eNamespaceProtoP\x01Z!go.temporal.io/api/enums/v1;enumsb\x06proto3'
)

_NAMESPACESTATE = _descriptor.EnumDescriptor(
  name='NamespaceState',
  full_name='temporal.api.enums.v1.NamespaceState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATE_REGISTERED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATE_DEPRECATED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE_STATE_DELETED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=65,
  serialized_end=207,
)
_sym_db.RegisterEnumDescriptor(_NAMESPACESTATE)

NamespaceState = enum_type_wrapper.EnumTypeWrapper(_NAMESPACESTATE)
_ARCHIVALSTATE = _descriptor.EnumDescriptor(
  name='ArchivalState',
  full_name='temporal.api.enums.v1.ArchivalState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATE_DISABLED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCHIVAL_STATE_ENABLED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=209,
  serialized_end=313,
)
_sym_db.RegisterEnumDescriptor(_ARCHIVALSTATE)

ArchivalState = enum_type_wrapper.EnumTypeWrapper(_ARCHIVALSTATE)
NAMESPACE_STATE_UNSPECIFIED = 0
NAMESPACE_STATE_REGISTERED = 1
NAMESPACE_STATE_DEPRECATED = 2
NAMESPACE_STATE_DELETED = 3
ARCHIVAL_STATE_UNSPECIFIED = 0
ARCHIVAL_STATE_DISABLED = 1
ARCHIVAL_STATE_ENABLED = 2


DESCRIPTOR.enum_types_by_name['NamespaceState'] = _NAMESPACESTATE
DESCRIPTOR.enum_types_by_name['ArchivalState'] = _ARCHIVALSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
