# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/tasklist/v1/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from temporal.enums.v1 import task_list_pb2 as temporal_dot_enums_dot_v1_dot_task__list__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='temporal/tasklist/v1/message.proto',
  package='temporal.tasklist.v1',
  syntax='proto3',
  serialized_options=b'\n\035io.temporal.proto.tasklist.v1B\014MessageProtoP\001Z2go.temporal.io/temporal-proto/tasklist/v1;tasklist',
  serialized_pb=b'\n\"temporal/tasklist/v1/message.proto\x12\x14temporal.tasklist.v1\x1a!temporal/enums/v1/task_list.proto\x1a\x1egoogle/protobuf/wrappers.proto\"G\n\x08TaskList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\x04kind\x18\x02 \x01(\x0e\x32\x1f.temporal.enums.v1.TaskListKind\"N\n\x10TaskListMetadata\x12:\n\x14max_tasks_per_second\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"\xa6\x01\n\x0eTaskListStatus\x12\x1a\n\x12\x62\x61\x63klog_count_hint\x18\x01 \x01(\x03\x12\x12\n\nread_level\x18\x02 \x01(\x03\x12\x11\n\tack_level\x18\x03 \x01(\x03\x12\x17\n\x0frate_per_second\x18\x04 \x01(\x01\x12\x38\n\rtask_id_block\x18\x05 \x01(\x0b\x32!.temporal.tasklist.v1.TaskIdBlock\"/\n\x0bTaskIdBlock\x12\x10\n\x08start_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x65nd_id\x18\x02 \x01(\x03\"A\n\x19TaskListPartitionMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x0fowner_host_name\x18\x02 \x01(\t\"Q\n\nPollerInfo\x12\x18\n\x10last_access_time\x18\x01 \x01(\x03\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x17\n\x0frate_per_second\x18\x03 \x01(\x01\"\x80\x01\n\x19StickyExecutionAttributes\x12\x38\n\x10worker_task_list\x18\x01 \x01(\x0b\x32\x1e.temporal.tasklist.v1.TaskList\x12)\n!schedule_to_start_timeout_seconds\x18\x02 \x01(\x05\x42\x63\n\x1dio.temporal.proto.tasklist.v1B\x0cMessageProtoP\x01Z2go.temporal.io/temporal-proto/tasklist/v1;tasklistb\x06proto3'
  ,
  dependencies=[temporal_dot_enums_dot_v1_dot_task__list__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_TASKLIST = _descriptor.Descriptor(
  name='TaskList',
  full_name='temporal.tasklist.v1.TaskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='temporal.tasklist.v1.TaskList.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='temporal.tasklist.v1.TaskList.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=198,
)


_TASKLISTMETADATA = _descriptor.Descriptor(
  name='TaskListMetadata',
  full_name='temporal.tasklist.v1.TaskListMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_tasks_per_second', full_name='temporal.tasklist.v1.TaskListMetadata.max_tasks_per_second', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=278,
)


_TASKLISTSTATUS = _descriptor.Descriptor(
  name='TaskListStatus',
  full_name='temporal.tasklist.v1.TaskListStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backlog_count_hint', full_name='temporal.tasklist.v1.TaskListStatus.backlog_count_hint', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_level', full_name='temporal.tasklist.v1.TaskListStatus.read_level', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack_level', full_name='temporal.tasklist.v1.TaskListStatus.ack_level', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate_per_second', full_name='temporal.tasklist.v1.TaskListStatus.rate_per_second', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id_block', full_name='temporal.tasklist.v1.TaskListStatus.task_id_block', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=447,
)


_TASKIDBLOCK = _descriptor.Descriptor(
  name='TaskIdBlock',
  full_name='temporal.tasklist.v1.TaskIdBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_id', full_name='temporal.tasklist.v1.TaskIdBlock.start_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_id', full_name='temporal.tasklist.v1.TaskIdBlock.end_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=496,
)


_TASKLISTPARTITIONMETADATA = _descriptor.Descriptor(
  name='TaskListPartitionMetadata',
  full_name='temporal.tasklist.v1.TaskListPartitionMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='temporal.tasklist.v1.TaskListPartitionMetadata.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_host_name', full_name='temporal.tasklist.v1.TaskListPartitionMetadata.owner_host_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=563,
)


_POLLERINFO = _descriptor.Descriptor(
  name='PollerInfo',
  full_name='temporal.tasklist.v1.PollerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_access_time', full_name='temporal.tasklist.v1.PollerInfo.last_access_time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='temporal.tasklist.v1.PollerInfo.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate_per_second', full_name='temporal.tasklist.v1.PollerInfo.rate_per_second', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=646,
)


_STICKYEXECUTIONATTRIBUTES = _descriptor.Descriptor(
  name='StickyExecutionAttributes',
  full_name='temporal.tasklist.v1.StickyExecutionAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_task_list', full_name='temporal.tasklist.v1.StickyExecutionAttributes.worker_task_list', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schedule_to_start_timeout_seconds', full_name='temporal.tasklist.v1.StickyExecutionAttributes.schedule_to_start_timeout_seconds', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=777,
)

_TASKLIST.fields_by_name['kind'].enum_type = temporal_dot_enums_dot_v1_dot_task__list__pb2._TASKLISTKIND
_TASKLISTMETADATA.fields_by_name['max_tasks_per_second'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_TASKLISTSTATUS.fields_by_name['task_id_block'].message_type = _TASKIDBLOCK
_STICKYEXECUTIONATTRIBUTES.fields_by_name['worker_task_list'].message_type = _TASKLIST
DESCRIPTOR.message_types_by_name['TaskList'] = _TASKLIST
DESCRIPTOR.message_types_by_name['TaskListMetadata'] = _TASKLISTMETADATA
DESCRIPTOR.message_types_by_name['TaskListStatus'] = _TASKLISTSTATUS
DESCRIPTOR.message_types_by_name['TaskIdBlock'] = _TASKIDBLOCK
DESCRIPTOR.message_types_by_name['TaskListPartitionMetadata'] = _TASKLISTPARTITIONMETADATA
DESCRIPTOR.message_types_by_name['PollerInfo'] = _POLLERINFO
DESCRIPTOR.message_types_by_name['StickyExecutionAttributes'] = _STICKYEXECUTIONATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskList = _reflection.GeneratedProtocolMessageType('TaskList', (_message.Message,), {
  'DESCRIPTOR' : _TASKLIST,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.TaskList)
  })
_sym_db.RegisterMessage(TaskList)

TaskListMetadata = _reflection.GeneratedProtocolMessageType('TaskListMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTMETADATA,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.TaskListMetadata)
  })
_sym_db.RegisterMessage(TaskListMetadata)

TaskListStatus = _reflection.GeneratedProtocolMessageType('TaskListStatus', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTSTATUS,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.TaskListStatus)
  })
_sym_db.RegisterMessage(TaskListStatus)

TaskIdBlock = _reflection.GeneratedProtocolMessageType('TaskIdBlock', (_message.Message,), {
  'DESCRIPTOR' : _TASKIDBLOCK,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.TaskIdBlock)
  })
_sym_db.RegisterMessage(TaskIdBlock)

TaskListPartitionMetadata = _reflection.GeneratedProtocolMessageType('TaskListPartitionMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TASKLISTPARTITIONMETADATA,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.TaskListPartitionMetadata)
  })
_sym_db.RegisterMessage(TaskListPartitionMetadata)

PollerInfo = _reflection.GeneratedProtocolMessageType('PollerInfo', (_message.Message,), {
  'DESCRIPTOR' : _POLLERINFO,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.PollerInfo)
  })
_sym_db.RegisterMessage(PollerInfo)

StickyExecutionAttributes = _reflection.GeneratedProtocolMessageType('StickyExecutionAttributes', (_message.Message,), {
  'DESCRIPTOR' : _STICKYEXECUTIONATTRIBUTES,
  '__module__' : 'temporal.tasklist.v1.message_pb2'
  # @@protoc_insertion_point(class_scope:temporal.tasklist.v1.StickyExecutionAttributes)
  })
_sym_db.RegisterMessage(StickyExecutionAttributes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
