# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasklist/enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasklist/enum.proto',
  package='tasklist',
  syntax='proto3',
  serialized_options=b'\n\032io.temporal.proto.tasklistP\001Z&go.temporal.io/temporal-proto/tasklist',
  serialized_pb=b'\n\x13tasklist/enum.proto\x12\x08tasklist*d\n\x0cTaskListKind\x12\x1e\n\x1aTASK_LIST_KIND_UNSPECIFIED\x10\x00\x12\x19\n\x15TASK_LIST_KIND_NORMAL\x10\x01\x12\x19\n\x15TASK_LIST_KIND_STICKY\x10\x02*h\n\x0cTaskListType\x12\x1e\n\x1aTASK_LIST_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17TASK_LIST_TYPE_DECISION\x10\x01\x12\x1b\n\x17TASK_LIST_TYPE_ACTIVITY\x10\x02\x42\x46\n\x1aio.temporal.proto.tasklistP\x01Z&go.temporal.io/temporal-proto/tasklistb\x06proto3'
)

_TASKLISTKIND = _descriptor.EnumDescriptor(
  name='TaskListKind',
  full_name='tasklist.TaskListKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_KIND_STICKY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTKIND)

TaskListKind = enum_type_wrapper.EnumTypeWrapper(_TASKLISTKIND)
_TASKLISTTYPE = _descriptor.EnumDescriptor(
  name='TaskListType',
  full_name='tasklist.TaskListType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_DECISION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_LIST_TYPE_ACTIVITY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_TASKLISTTYPE)

TaskListType = enum_type_wrapper.EnumTypeWrapper(_TASKLISTTYPE)
TASK_LIST_KIND_UNSPECIFIED = 0
TASK_LIST_KIND_NORMAL = 1
TASK_LIST_KIND_STICKY = 2
TASK_LIST_TYPE_UNSPECIFIED = 0
TASK_LIST_TYPE_DECISION = 1
TASK_LIST_TYPE_ACTIVITY = 2


DESCRIPTOR.enum_types_by_name['TaskListKind'] = _TASKLISTKIND
DESCRIPTOR.enum_types_by_name['TaskListType'] = _TASKLISTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
